args:
  name: gpt-oss-20b
  gpu_type: nvidia-h100-80gb
  tp: 1
  metadata:
    description: GPT OSS MoE 20B
    provider: OpenAI
    gpu_recommendation: Nvidia GPUs with at least 80GB VRAM (e.g about 1 H100 GPU).
  model_id: openai/gpt-oss-20b
  exclude:
    - "original/**/*"
    - "metal/**/*"
  skip_flashinfer: true
  reasoning_parser: openai_gptoss
  tool_parser: openai
  cli_args:
    - '--chat-template'
    - 'templates/tool_gpt_oss.jinja'
  envs:
    - name: HF_TOKEN
