args:
  name: gpt-oss-120b
  gpu_type: nvidia-h100-80gb
  tp: 4
  metadata:
    description: GPT OSS MoE 120B
    provider: OpenAI
    gpu_recommendation: Nvidia GPUs with at least 140GB VRAM (e.g about 1 H200 GPU or 2xH100 GPUs).
  model_id: openai/gpt-oss-120b
  exclude:
    - "original/**/*"
    - "metal/**/*"
  skip_flashinfer: true
  tool_parser: openai
  reasoning_parser: openai_gptoss
  cli_args:
    - '--chat-template'
    - 'templates/tool_gpt_oss.jinja'
  envs:
    - name: HF_TOKEN
